// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/admin/content" | "/admin/products" | "/admin/site" | "/affiliate" | "/blogs" | "/blogs/[slug]" | "/contact" | "/privacy-policy" | "/product/[slug]" | "/refund-policy" | "/returns" | "/shipping-policy" | "/shop" | "/terms" | "/track-order"
type AppRouteHandlerRoutes = "/api/content" | "/api/forms/affiliate" | "/api/forms/contact" | "/api/forms/newsletter" | "/api/manual-products" | "/api/orders/track" | "/api/site-config" | "/api/uploads/model"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/admin": {}
  "/admin/content": {}
  "/admin/products": {}
  "/admin/site": {}
  "/affiliate": {}
  "/api/content": {}
  "/api/forms/affiliate": {}
  "/api/forms/contact": {}
  "/api/forms/newsletter": {}
  "/api/manual-products": {}
  "/api/orders/track": {}
  "/api/site-config": {}
  "/api/uploads/model": {}
  "/blogs": {}
  "/blogs/[slug]": { "slug": string; }
  "/contact": {}
  "/privacy-policy": {}
  "/product/[slug]": { "slug": string; }
  "/refund-policy": {}
  "/returns": {}
  "/shipping-policy": {}
  "/shop": {}
  "/terms": {}
  "/track-order": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
