"use client";

import { ChangeEvent, DragEvent, useRef, useState } from "react";

export function ModelUploader({ value, onChange }: { value: string; onChange: (path: string) => void }) {
  const input = useRef<HTMLInputElement>(null); const [status, setStatus] = useState(""); const [dragging, setDragging] = useState(false);
  async function upload(file?: File) { if (!file) return; if (!file.name.toLowerCase().endsWith(".glb")) { setStatus("Please select a .glb file."); return; } if (file.size > 20 * 1024 * 1024) { setStatus("GLB files must be 20 MB or smaller."); return; } setStatus("Uploading model..."); try { const data = new FormData(); data.append("file", file); const response = await fetch("/api/uploads/model", { method: "POST", body: data }); const result = await response.json(); if (!response.ok) throw new Error(result.error); onChange(result.path); setStatus("Model uploaded."); } catch (error) { setStatus(error instanceof Error ? error.message : "Model upload failed."); } }
  return <div className={`model-uploader ${dragging ? "dragging" : ""}`} onDragOver={event => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); void upload(event.dataTransfer.files[0]); }}><input ref={input} className="sr-only" type="file" accept=".glb,model/gltf-binary" onChange={(event: ChangeEvent<HTMLInputElement>) => void upload(event.target.files?.[0])}/><strong>{value ? "Current GLB model" : "Upload GLB model"}</strong><span>{value || "Drop a .glb file here, or choose it from your computer."}</span><div><button type="button" className="admin-secondary-button" onClick={() => input.current?.click()}>{value ? "Replace file" : "Choose file"}</button>{value && <button type="button" className="admin-secondary-button" onClick={() => onChange("")}>Remove</button>}</div><small aria-live="polite">{status || "Maximum file size: 20 MB. Local development storage: public/uploads/models."}</small></div>;
}
