"use client";
import { useEffect, useState } from "react";
import type { ShopifyAdminOrderDetail, ShopifyAdminOrderSummary } from "@/lib/shopify-admin/commerce";

export function OrdersAdmin() {
  const [orders, setOrders] = useState<ShopifyAdminOrderSummary[]>([]); const [state, setState] = useState<"loading" | "ready" | "disconnected" | "error">("loading"); const [message, setMessage] = useState(""); const [detail, setDetail] = useState<ShopifyAdminOrderDetail | null>(null); const [detailState, setDetailState] = useState<"idle" | "loading" | "error">("idle");
  useEffect(() => { fetch("/api/admin/orders", { cache: "no-store" }).then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error || "Orders could not be loaded."); if (!data.connected) { setState("disconnected"); return; } setOrders(data.orders); setState("ready"); }).catch(error => { setMessage(error instanceof Error ? error.message : "Orders could not be loaded."); setState("error"); }); }, []);
  async function showOrder(id: string) { setDetailState("loading"); setDetail(null); try { const r = await fetch(`/api/admin/orders/${encodeURIComponent(id)}`, { cache: "no-store" }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Order detail could not be loaded."); setDetail(data.order); setDetailState("idle"); } catch (error) { setMessage(error instanceof Error ? error.message : "Order detail could not be loaded."); setDetailState("error"); } }
  if (state === "loading") return <p className="admin-message">Loading Shopify orders...</p>;
  if (state === "disconnected") return <p className="admin-help">Connect `SHOPIFY_ADMIN_ACCESS_TOKEN` to load real Shopify orders. No demo orders are shown.</p>;
  if (state === "error") return <p className="admin-message">{message}</p>;
  return <div className="orders-admin-list">{orders.length === 0 ? <p className="admin-empty">No Shopify orders found.</p> : orders.map(order => <article key={order.id}><button type="button" className="order-row-button" onClick={() => showOrder(order.id)}><div><strong>{order.name}</strong><span>{new Date(order.createdAt).toLocaleString()} · {order.customer?.displayName || "Guest"}</span></div><div><span className="order-status">{order.financialStatus}</span><span className="order-status">{order.fulfillmentStatus}</span><strong>{order.total.currencyCode} {order.total.amount}</strong></div></button></article>)}{detailState === "loading" && <p className="admin-message">Loading order detail...</p>}{detailState === "error" && <p className="admin-message">{message}</p>}{detail && <OrderDetail detail={detail} onClose={() => setDetail(null)} />}</div>;
}

function OrderDetail({ detail, onClose }: { detail: ShopifyAdminOrderDetail; onClose: () => void }) { const address = detail.shippingAddress ? [detail.shippingAddress.name, detail.shippingAddress.address1, detail.shippingAddress.address2, detail.shippingAddress.city, detail.shippingAddress.province, detail.shippingAddress.zip, detail.shippingAddress.country].filter(Boolean).join(", ") : "No shipping address."; return <section className="admin-order-detail"><button type="button" className="icon-btn" onClick={onClose} aria-label="Close order detail">×</button><span className="eyebrow">ORDER DETAIL</span><h2>{detail.name}</h2><p>{detail.customer?.displayName || "Guest"} · {detail.email || detail.customer?.email || "No email available"}</p><div className="admin-order-detail-grid"><div><strong>Items</strong>{detail.lineItems.map((item, i) => <p key={`${item.title}-${item.sku || i}`}>{item.quantity}× {item.title}{item.variantTitle ? ` — ${item.variantTitle}` : ""} · {item.unitPrice.currencyCode} {item.unitPrice.amount}</p>)}</div><div><strong>Shipping address</strong><p>{address}</p></div><div><strong>Payment</strong>{detail.transactions.length ? detail.transactions.map((t, i) => <p key={`${t.gateway}-${i}`}>{t.gateway} · {t.kind} · {t.status} · {t.amount.currencyCode} {t.amount.amount}</p>) : <p>{detail.financialStatus}</p>}</div><div><strong>Fulfillment & tracking</strong>{detail.fulfillments.length ? detail.fulfillments.map((f, i) => <p key={`${f.status}-${i}`}>{f.status}{f.tracking.map(track => ` · ${track.company || "Carrier"}: ${track.number || "Pending"}`).join("")}</p>) : <p>{detail.fulfillmentStatus}</p>}</div></div></section>; }
